### PR TITLE
Remove user id from user routes

### PR DESCRIPTION
**Pull request by brandiseeley**
Previously, the routes to get a users data required us to include the `user_id` in the path. Because we're only concerned with fetching data for the currently logged in user, I've removed this dependency. Maybe we'll need both eventually, like once users interact with each other, but for now I'd like to focus on exactly what we need for the front end.

This change has only been made to these two endpoints:

~~`/gorapass/users/<user_id>/completed_hikes`~~ -> `/gorapass/users/completed_hikes`

~~`/gorapass/users/<user_id>/completed_stamps`~~ -> `/gorapass/users/completed_stamps`

### CODE REVIEW

**Comment by sayan-gg** [comment]
This looks fine to me, especially because then I think it's harder for malicious users to try to hack into routes they aren't authorized to access (if we somehow forgot to protect that route, it's pretty easy for someone to guess there's a user id of 1 and check that route). 

My question is if we are removing the user_id part of the URL, is there a point in keeping the `/users/` part of the URL?

**Review by sayan-gg — APPROVED** [review]

**Comment by brandiseeley** [comment]
Hmmm, yeah we could. My thinking was that having `users` namespaces the routes so that whenever you use `users/*`, you know that what you're getting back is specific to that user. That was my thinking anyways, but maybe it overcomplicated it. What do you think, @sayan-gg?

**Comment by sayan-gg** [comment]
I don’t have a strong opinion. We can keep /users/ in the route for user-specific info, that makes sense to me.On Aug 21, 2024, at 7:25 AM, Brandi Seeley ***@***.***> wrote:﻿
Hmmm, yeah we could. My thinking was that having users namespaces the routes so that whenever you use users/*, you know that what you're getting back is specific to that user. That was my thinking anyways, but maybe it overcomplicated it. What do you think, @sayan-gg?

**Review by sayan-gg — APPROVED** [review]

**Comment by sayan-gg** [comment]
I decided to go ahead and merge this because I needed these changes to handle some front end stuff

**Pull request merged**
